import argparse
# from memory_profiler import profile
import json
import sys
from pathlib import Path
from pprint import pprint
import html


def read_json(path: Path):
    with path.open(mode='r', encoding='utf-8') as f:
        raw = html.unescape(f.read())
        article = json.loads(raw)
    return article


def main(json_path: str):
    path = Path(json_path)
    article = read_json(path)
    return article
    
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--json_path',
        help='jsons\'s path generated by niconico-parser via web',
        type=str)
    args = parser.parse_args(args=['--json_path', '../三枝明那.json'])
    # main(args.json_path)
    print(main("./resources/エクス・アルビオ.json"))
    