import argparse

def main(args):
    print(args)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--json_folder',
        help='jsons\'s folder path generated by niconico-parser via web',
        type=str,
        default='resources')

    parser.add_argument(
        '--reset_db',
        action="store_true",
        help="reset the mongo db"
    )

    args = parser.parse_args()
    main(args)
    # args = parser.parse_args(args=['store', '--json_folder', 'resources'])
    # main(args.json_path)
    # main("三枝明那.json")