import argparse
# from memory_profiler import profile
import json
import sys
from pathlib import Path
from pprint import pprint

from service import absts, contents, related_words, utils

sys.path.append('../')



def read_json(path: Path):
    with path.open(mode='r', encoding='utf-8') as f:
        article = json.load(f)
    return article


def main(json_path: str):
    path = Path(json_path)
    article = read_json(path)
    title = utils.get_element(article, 'title')
    rrw, rw = related_words.extract_item(article)
    keywords = article.get('keywords', [])
    abstruct, _, left = absts.extract_abstruct(article['article'])
    pprint(title)
    pprint(keywords)
    pprint(rw)
    pprint(abstruct)
    section,_ = contents.SectionParser()(left)
    pprint(section)
    


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--json_path',
        help='jsons\'s path generated by niconico-parser via web',
        type=str)
    args = parser.parse_args(args=['--json_path', '../三枝明那.json'])
    main(args.json_path)
